application: edmundoferreirainfo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css
  static_dir: static/css
  
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: .*
  script: wiki.app


libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
